[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.158"
tokio = { version = "1", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
